### ISSUE TITLE
Change the icon on the TheGraph main page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/subgraph#67]
Open https://thegraph.com/hosted-service/subgraph/cowprotocol/cow
Check the icon

**AR**: it is an outdated one
![image](https://user-images.githubusercontent.com/70885163/196463122-14d09cf4-b564-4658-bb5f-8eb5b7e3884b.png)

**ER**: need to change the icon to the rebranded one
![image](https://user-images.githubusercontent.com/70885163/196463313-183f3c1c-c138-41d5-889f-4df8f2eb5d8a.png)

**Comment by anxolin** [comment]
Fixed! thanks Elena for the reminder
